### ISSUE TITLE
Storyboard Support.

### ISSUE THREAD

**Issue by iAviatorJose** [nairteashop/NTMonthYearPicker#5]
On creating a outlet of NTMonthYearPickerView, it gives the below error

`/Users/Jose/Development/Projects/my-budget-ios/mezaniti/MonthYearPickerVC.swift:18:24: 'weak' may only be applied to class and class-bound protocol types, not '<<error type>>'`

**Comment by nathanmrtns** [comment]
@iAviatorJose you should import NTMonthYearPicker on your MonthYearPickerVC
